---
- name: Install EPEL release for nginx
  yum:
    name: epel-release
    state: present

- name: Upadate repo and install nginx
  yum: 
    name: nginx
    state: installed
    update_cache: true
  notify: Ensure nginx is added to autostart and started


