---
- name: Install Nginx
  include_tasks: "{{ ansible_distribution }}.yml"

- name: Remove nginx default conifg
  file:
    path: '{{ nginx_path }}/sites-enabled/default'
    state: absent
  notify: Reload Nginx

- name: Setting nginx general configuration
  template:
    src: 'nginx.conf.j2'
    dest: '{{ nginx_path }}/nginx.conf'
  notify: Reload Nginx
