---
- name: Ensure virtualhosts direcry is created
  file:
    path: '{{ www_root }}/{{ hostname }}'
    state: directory

- name: Add virtual host config file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
     - { src: 'virtualhost.com.conf.j2', dest: '{{ nginx_path }}/sites-enabled/{{ hostname }}.conf' }
     - { src: 'index.html.j2', dest: '{{ www_root }}/{{ hostname }}/index.html' }
  notify: Reload Nginx
